<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	  <Version>3.2.4</Version>
	  <AssemblyVersion>3.2.2.0</AssemblyVersion>
	  <FileVersion>3.2.2.0</FileVersion>
	  <InformationalVersion>3.2.4 (Not Released)</InformationalVersion>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
	  <ApplicationIcon>Assets\MaterialReqAppIcon.ico</ApplicationIcon>
	  
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\CenterPointLogo_DarkText.png" />
    <None Remove="Assets\CenterPointLogo_LightText.png" />
    <None Remove="Assets\MaterialReqAppIcon.ico" />
    <None Remove="Templates\Material_Requisition_Issue_Fillable.pdf" />
    <None Remove="Templates\Material_Requisition_Return_Fillable.pdf" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Templates\Material_Requisition_Issue_Fillable.pdf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Templates\Material_Requisition_Return_Fillable.pdf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Syncfusion.Licensing" Version="32.1.19" />
    <PackageReference Include="Syncfusion.Pdf.Net.Core" Version="32.1.19" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\CenterPointLogo_DarkText.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\CenterPointLogo_LightText.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\MaterialReqAppIcon.ico" />
  </ItemGroup>

</Project>
