<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	  
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Templates\Material_Requisition_Issue_Fillable.pdf" />
    <None Remove="Templates\Material_Requisition_Return_Fillable.pdf" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Templates\Material_Requisition_Issue_Fillable.pdf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Templates\Material_Requisition_Return_Fillable.pdf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Syncfusion.Licensing" Version="32.1.19" />
    <PackageReference Include="Syncfusion.Pdf.Net.Core" Version="32.1.19" />
  </ItemGroup>

</Project>
